name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb -O pandoc.deb
          sudo dpkg -i pandoc.deb
          python -m pip install -r requirements.txt

      - name: Convert HTML
        run: |
          python convert.py --dest_fname index

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          FOLDER: converted